### ISSUE TITLE
[Bug] - Zoom guide

### ISSUE THREAD

**Issue by sempsmahad** [DoozyDoz/PassMath#33]
### Description
- There appears a zoom guide (button with zoom in and out options) every time while swiping the cards , I get its meant to help but its distracting and should be removed, a user can pinch to zoom in and out at will

**Comment by DoozyDoz** [comment]
@DoozyDoz I don't that will be possible, the "guide" is part of the `MathView` library

**Comment by sempsmahad** [comment]
Surprisingly I got a fast reply and it indeed helped

**Comment by DoozyDoz** [comment]
Good
